main: cn.wode490390.nukkit.luckyblock.LuckyBlock
name: "LuckyBlock"
description: "Lucky block plugin for Nukkit"
author: "wode490390"
website: "http://wode490390.cn/"
version: "${pom.version}"
api: ["1.0.0"]
load: POSTWORLD
permissions:
  luckyblock.trigger:
    description: "Allows player to trigger lucky block"
    default: true
